server:
  port: 8080
spring:
  banner:
    location: logo.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:file:./h2database
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
chatgpt:
  token: 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
homecast:
  ip: http://192.168.1.110:8080
  imagesdir: C:\HomeCast\images\
  mp4dir: C:\HomeCast\mp4\
  homecastdir: C:\HomeCast\