server:
  port: 8080
spring:
  banner:
    location: logo.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
chatgpt:
  token: token
homecast:
  ip: http://192.168.1.107:8080
  imagesdir: C:\HomeCast\images\
  mp4dir: C:\HomeCast\mp4\