server:
  port: 8080
spring:
  banner:
    location: logo.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:file:${homecast.homecastdir}/h2database
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
chatgpt:
  token: token
  isTokenActive: false
homecast:
  ip: http://192.168.1.110:${server.port}
  homecastdir: C:\HomeCast\
  imagesdir: ${homecast.homecastdir}\images\
  mp4dir: ${homecast.homecastdir}\mp4\
